###
GET http://localhost:8080/department/5/salary/max
###
GET http://localhost:8080/department/4/salary/min
###
GET http://localhost:8080/department/5/salary/sum
###
GET http://localhost:8080/department/5/employees
###
GET http://localhost:8080/department/employees
###

GET http://localhost:8080/employees-book/add?firstName=Sergei&lastName=Gots&departmentId=5&salary=370000
###
GET http://localhost:8080/employees-book/find?firstName=Афанасий&lastName=никитин
###
GET http://localhost:8080/employees-book/find?firstName=Михаил&lastName=глинка
###
GET http://localhost:8080/employees-book/remove?firstName=Афанасий&lastName=никитин
###
